# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Gaurav Ashtikar
description: "Gaurav Ashtikar Resume"
keywords: "Gaurav, Ashtikar, resume"
url: http://gau1991.me
baseurl: ""

# Author settings
author:
  name      : Gaurav Ashtikar
  gravatar  : b870ad36ac8e56abaabdb2640fba4bbf
  job       : Linux System Administrator
  bio       : "Linux and Open Source maniac, passionate to solve problems in real world"
  email     : gau1991@gmail.com
  url       : http://gau1991.github.io
  github    : http://github.com/gau1991
  twitter   : http://twitter.com/gau1992
  facebook  : http://facebook.com/gau1991
  linkedin  : http://linkedin.com/in/gau1991
  googleplus : https://plus.google.com/+GauravAshtikar1

# navbar pages
navbar:
  - slug: resume
    title: Resume

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
