# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Shashank Sonawane
description: "Shashank Sonawane Resume"
keywords: "Shashank, Sonawane, resume"
url: http://shashankprofile.github.me
baseurl: ""

# Author settings
author:
  name      : Shashank Sonawane
  gravatar  : b870ad36ac8e56abaabdb2640fba4bbf
  job       : Technical Account Engineer
  bio       : "DHCP,SIP,VOICE IP Provisining expert, Linux,shell,java debugger, passionate to solve problems in real world"
  email     : shashankss.sonawane@gmail.com
  url       : http://shashankprofile.github.me
  github    : http://shashankprofile.github.me
  twitter   : http://shashankprofile.github.me
  facebook  : http:://shashankprofile.github.me
  linkedin  : http:://shashankprofile.github.me
  googleplus : https://shashankprofile.github.me

# navbar pages
navbar:
  - slug: resume
    title: Resume

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
